# Generated by Django 5.1.1 on 2024-09-06 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bimar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('explainations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Khedmat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nobat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('bimar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bimar_app.bimar')),
                ('khedmat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bimar_app.khedmat')),
            ],
        ),
    ]
